### PR TITLE
Separate plotting from simulation

### LINKED ISSUE #15: Separate plotting from simulation
Currently the plotting is built into executing a simulation. We need these to be separate things to allow this script to be used in alternate applications (e.g., web).

### PR DESCRIPTION
**Pull request by agarny**
Addresses issue #15.

### CODE REVIEW

**Comment by agarny** [comment]
@nickerso, would this PR work for you with regards to what you need to do from the website?

**Comment by nickerso** [comment]
In general, looks like it would do the trick. One suggestion though, is that you should keep running a simulation and resetting the results separate. This will allow a user to run for a bit, make changes to parameter values, run for a bit more, make changes, run... without having to build their own duplicate cache of simulation results. i.e., let the user choose when to reset the internal value cache.

**Comment by agarny** [comment]
Fair point. Will do that tomorrow now that I have switched to CellML 2.0 and Keri is waiting... :)

**Comment by agarny** [comment]
To rename `Model.__reset()` to `Model.reset()` should do the trick, as well as remove the call to `self.__reset()` from `Model.run()`.

**Comment by agarny** [comment]
Ok, @nickerso, I have done the changes you are after. This should now be ready to merge.

**Review by nickerso — APPROVED** [review]

**Pull request merged**
